### ISSUE TITLE
Example is not compiled, so it's bitrotten

### ISSUE THREAD

**Issue by Blaisorblade** [ekmett/intern#7]
Dear Edward, thanks for this library! I'm interested in using it.*

However the example has a couple of problems:
1. The example is not compiled, so it's of course going to rot. Could you add it to the cabal file as executable? (Sorry, I'm not experienced enough with Cabal yet to do this right away).
2. Well, it already happened — it doesn't compile right now with some error for identify. #6 fixes it for now, but doesn't fix problem 1. Looking at the history, I'm guessing the single example is broken as of 2011 because of 3a0a372c7a46dbfd6a389866c2c1f6e17af05af1.

*I suspect I might need this to intern names in some other project (a typechecker for a crazy calculus), and I'm fine with not releasing interned names (because all names come from user programs, which are small).

**Comment by RyanGlScott** [comment]
As of fec109f834e3390d650d5e5178898b83502597ae, we now build the example on CI builds.
